{
    "contest": "rhg2019",
    "api_base": "https://172.16.4.1/api",
    "reset_env_after_fail_attempt":{
        "attack": false,
        "defend": false
    },
    "vuls": {
        "CVE_2016_10033": {
            "matcher": "recognizer/CVE_2016_10033.py",
            "exploit": [
                "exploit/CVE_2016_10033.py"
            ],
            "fix": [
                "fix/CVE_2016_10033.py"
            ]
        }
    }
}